pakit :
  command:
    timeout: 120
  defaults:
    repo: unstable
  log:
    enabled: true
    file: /tmp/myscripts_pakit_main.log
    level: debug
  paths:
    link: /home/starcraftman/.opt
    prefix: /home/starcraftman/.opt/builds
    recipes: /home/starcraftman/.pakit
    source: /tmp/pakit/src
  recipe:
    update_interval: 86400
    uris:
    - uri: https://github.com/pakit/base_recipes
    - uri: user_recipes
parallel:
  repo: stable
vimpager:
  repo: stable
