#!/usr/bin/env bash
usage()
{
    echo "${0##*/} haystack needle
    Exits true only if needle is in haystack."
}

if [ "$#" -ne 2 ]; then
    usage
    exit
fi

string="$1"
substring="$2"
if [ "${string#*$substring}" != "$string" ]; then
    exit 0    # $substring is in $string
else
    exit 1
fi
