#!/bin/bash

#Fill in these two with the device number of the mbr and root partition.
MBR_PART=
ROOT_PART=

# Fill in these two with path to store image files.
MBR_IMG=
ROOT_IMG=

# Opts for the command.
OPTS="bs=4096 conv=noerror"

usage() {
    echo "Usage: ${0##*/} <direction> "
    echo "The <direction> can be of the following:"
    echo "restore: Copies existing images over root and mbr."
    echo "backup: Copies existing partitions over images."
}

restore() {
    sudo dd if=$MBR_IMG of=$MBR_PART $OPTS
    sudo dd if=$ROOT_IMG of=$ROOT_PART $OPTS
}

backup() {
    sudo dd if=$MBR_PART of=$MBR_IMG $OPTS
    sudo dd if=$ROOT_PART of=$ROOT_IMG $OPTS
}


if [ ! -n $1 ]; then
    usage
    exit
fi

if [ -z $1 ]; then
    usage
    exit
fi

if [ -z "$MBR_IMG" -o -z "$MBR_PART" -o -z "$ROOT_IMG" -o -z "$ROOT_PART" ]; then
    echo "You need to fill in information in script, see comments."
    exit
fi
exit

if [ "$1" = "backup" ]; then
    restore
elif [ "$1" = "restore" ]; then
    backup
else
    echo "Command not suported."
    usage
    exit
fi

