#!/bin/bash

function usage() {
	echo "Usage: ${0##*/} file1.cpp file2.hpp ..."
}

if [ -z  $1 ]; then
        usage
        exit 
fi

# Takes argument 1 as a filename. 
function make_file() {
	ext="${1##*.}"

	if [ "$ext" == "cpp" ]; then
  		cp ~/.my_scripts/templates/c++_template.cc "$1"
	elif [ "$ext" == "hpp" ]; then
 		def_name=`echo $1 | tr '[:lower:]' '[:upper:]' | tr '.' '_'`
 		cp ~/.my_scripts/templates/c++_template.h "$1"
 		sed -i s/_TEST_H_/"_"$def_name"_"/g "$1"
	else
		echo "That extension isn't supported. $1"
	fi
}

for var in "$@"
do
    make_file "$var"
done
