#!/bin/bash

function usage() {
	echo "Usage: ${0##*/} file1.pl file2.pl ..."
}

# Takes argument 1 as a filename. 
function make_file() {
	ext="${1##*.}"

	if [ "$ext" == "lisp" ]; then
		cp ~/.my_scripts/templates/lisp_template.lisp "$1"
	else
		echo "That extension isn't supported. $1"
		usage
		exit
	fi
}

if [ ! -n  $1 ]; then
	usage
	exit 
fi

if [ -z $1 ]; then
	usage
	exit
fi

for var in "$@"
do
    make_file "$var"
done
