#!/bin/bash

DEF_REPO=(~/.my_scripts ~/programming/AcademicProgramming ~/programming/JavaWork)

function usage() {
	echo "Usage: ${0##*/} repo1 repo2 ..."
}

# Takes argument 1 as a directory to update. 
function update_repo() {
	echo "$1"
	cd $1
	git pull
	cd -
}

if [ -z $1 ]; then
	for var in "${DEF_REPO[@]}"
	do
	    update_repo "$var"
	done
	exit 
fi

for var in "$@"
do
    update_repo "$var"
done
