#!/usr/bin/env bash
echo 'updating platform'
sudo apt-get update && sudo apt-get -y dist-upgrade
sudo apt-get autoremove
sudo apt-get -f install
vim +PluginUpdate +qa

echo 'updating git repos'
pushd .

DIR=~/.hg-prompt
if [[ -d $DIR ]]; then
  cd $DIR
  hg pull
fi

DIR=~/.bash-git-prompt
if [[ -d $DIR ]]; then
  cd $DIR
  git pull
fi

DIR=~/.hhighlighter
if [[ -d $DIR ]]; then
  cd $DIR
  git pull
fi

popd

# Force ag/ack update
echo 'updating ack and ag'
\rm -Rf ~/.ag ~/.ack
sysInstall.py 2 > /dev/null 2>&1
echo 'done'
