#!/usr/bin/env bash
#REPOS=( ~/.shell/.[^.]* ~/.shell/..?* ~/.my_scripts )
REPOS=( ~/.shell/* ~/.my_scripts )

# Update repositories passed as arguments
update_repos() {
    echo 'updating repos'
    pushd .

    for dir ; do
        if [ -d "$dir" ]; then
            cd "$dir"
            echo -e " >>> ${T_BGREEN}$dir${T_RESET} <<< "
            if [ -d ".git" ]; then
                git pull && git submodule update --init --recursive
            elif [ -d ".hg" ]; then
                hg pull && hg update
            fi
        fi
    done

    popd
}

update_repos "${REPOS[@]}"

if [ -f ~/.vim/autoload/plug.vim ]; then
    echo 'Updating vim plugins.'
    vim +PlugUpdate +PlugUpgrade +qa
fi

if valid_name apt-get; then
    echo 'updating debian platform'
    sudo apt-get update && sudo apt-get -y dist-upgrade
    sudo apt-get autoremove
    sudo apt-get -f install
fi

if [ -d "$OPTDIR" ]; then
    echo 'Updating programs built with pakit.'
    HERE=$(readlink -f $(dirname "$0"))
    pakit --conf "$HERE/.pakit.yml" update
fi

echo 'done'
