#!/usr/bin/env bash
# Function returns true only if name exists in path, else false
usage()
{
    echo "${0##*/} name
    Exits true only if name exists on the path."
}

if [ "$#" -ne 1 -o "$1" == '--help' -o "$1" == '-h' ]; then
    usage
    exit
fi

case "$(type -t "$1")" in
    alias|builtin|function|keyword)
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
