#!/bin/sh

# Zero drive before backup, writes zeros until drive full then deletes file
# Run ON mounted target drive
#dd if=/dev/zero of=./delete.me bs=8M; \rm ./delete.me

# Backup mbr, restore reverse if/of
#dd if=/dev/sdb of=./mbr.img bs=512 count=1 conv=sync,noerror

# Backup partition
#dd if=/dev/sdb2 conv=sync,noerror bs=64K | gzip -c > ./Win7_C.img.gz

# Restore partition
#gunzip -c ./Win7_C.img.gz | dd of=/dev/sdb2 conv=sync,noerror bs=64K

