#!/bin/sh
PYTHON_URL=https://www.python.org/ftp/python/2.7.8/Python-2.7.8.tar.xz
ZSH_URL=https://github.com/zsh-users/zsh.git

build_py()
{
  local py_arc=python.tar.xz
  curl PYTHON_URL > "$py_arc"
  unarchive "$py_arc"
  pushd python*
  ./condigure --prefix=$OPT
  make
  make install
  popd
}


build_zsh()
{
  git clone https://github.com/zsh-users/zsh.git
  pushd zsh
  ./condigure --prefix=$OPT
  make
  make install
  popd
}

print "Simple bootstrapper to get python & zsh on systems that might\
  not have packages for it."
